# Python support can be specified down to the minor or micro version
# (e.g. 3.6 or 3.6.3).
# OS Support also exists for jessie & stretch (slim and full).
# See https://hub.docker.com/r/library/python/ for all supported Python
# tags from Docker Hub.
FROM python:3
COPY . .
WORKDIR /popular_spider
RUN pip3 install -r requirements.txt
CMD ["./run.sh"]
